NT_Valdymo_Sistema/NT_Valdymo_Sistema/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NT_Valdymo_Sistema.Models;
using System.Data.Entity;
using System.Net;
using System.Drawing;
using System.IO;
using System.Data.SqlTypes;

namespace NT_Valdymo_Sistema.Controllers
{

    public class ReportController : Controller
    {
        private REDatabaseEntities db = new REDatabaseEntities();

        // GET: AdList
        public ActionResult AccountantMainWindow()
        {
            return View();
        }

        public ActionResult AdViewWindow()
        {
            return View(db.Advertisement.ToList());
        }

        [HttpGet]
        public ActionResult AdReportWindow()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdReportWindow(AdReport adReport)
        {
            string message = "";

            if (ModelState.IsValid)
            {
                using (REDatabaseEntities dc = new REDatabaseEntities())
                {
                    message = "Sudaryta ataskaita!";
                    int priceFrom = Convert.ToInt32(adReport.PriceFrom);
                    int priceTo = Convert.ToInt32(adReport.PriceTo);
                    var neededAds = new List<Advertisement>();
                    var neededAds2 = new List<Advertisement>();
                    var neededAds3 = new List<Advertisement>();
                    var cities = new List<String>();
                    var count = new List<int>();
                    var ads = dc.Advertisement;
                    var houses = dc.House;

                    foreach (var ad in ads)
                    {
                        neededAds2.Add(dc.Advertisement.Where(a => a.HouseID == ad.House.HouseID).First());
                    }

                    neededAds3 = (neededAds2.Where(a => a.Price <= priceTo).ToList());
                    neededAds = (neededAds3.Where(a => a.Price >= priceFrom).ToList());

                    cities = neededAds.GroupBy(x => x.House.Municipality).Where(group => group.Count() > 0).Select(group => group.Key).ToList();

                    count = neededAds.GroupBy(x => x.House.Municipality).Where(group => group.Count() > 0).Select(group => group.Count()).ToList();

                    var all = neededAds.GroupBy(i => i.House.Municipality).Select(g => new { Municipality = g.Key, Count = g.Count(), Average = g.Average(i => i.Price) }).ToString();

                    var average = neededAds.GroupBy(i => i.House.Municipality).Where(group => group.Count() > 0).Select(g => new { Average = g.Average(i => i.Price)});

                    ViewBag.cities = cities;
                    ViewBag.count = count;
                    ViewBag.average = average;
                    ViewBag.all = all;
                }
            }

            ViewBag.Message = message;

            return View(adReport);
        }

        public ActionResult SpecificAdWindow(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advertisement advertisement = db.Advertisement.Find(id);
            if (advertisement == null)
            {
                return HttpNotFound();
            }
            return View(advertisement);
        }

        public ActionResult REReportWindow()
        {
            return View();
        }

        public ActionResult REViewWindow()
        {
            return View();
        }

        public ActionResult SpecificREWindow(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Declaration declaration = db.Declaration.Find(id);
            if (declaration == null)
            {
                return HttpNotFound();
            }
            return View(declaration);
        }

        [HttpGet]
        public ActionResult AdFilterWindow()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdFilterWindow(AdReport adReport)
        {
            string message = "";

            if (ModelState.IsValid)
            {
                using (REDatabaseEntities dc = new REDatabaseEntities())
                {
                    message = "Filtro nustatymai atlikti!";
                    int priceFrom = Convert.ToInt32(adReport.PriceFrom);
                    int priceTo = Convert.ToInt32(adReport.PriceTo);
                    var neededAddresses = new List<String>();
                    var neededHouse = new List<String>();
                    var ads = new List<Advertisement>();
                    var neededAds = new List<Advertisement>();
                    var houses = new List<House>();

                    ads = dc.Advertisement.Where(x => x.Price <= priceTo).ToList();
                    neededAds = ads.Where(x => x.Price >= priceFrom).ToList();

                    foreach (var ad in neededAds)
                    {
                        houses.Add(dc.House.Where(a => a.HouseID == ad.HouseID).First());
                    }

                    for (int i = 0; i < houses.Count; i++)
                    {
                        neededAddresses.Add(houses[i].Settlement + ", " + houses[i].Street + " " + houses[i].HouseNr);
                        neededHouse.Add(houses[i].BuildingType);
                    }

                    ViewBag.neededAds = neededAds;
                    ViewBag.neededAddress = neededAddresses;
                    ViewBag.neededHouse = neededHouse;
                }
            }
            ViewBag.Message = message;
            return View(adReport);
        }

        public ActionResult REFilterWindow()
        {
            return View();
        }
    }
}

NT_Valdymo_Sistema/NT_Valdymo_Sistema/Views/Shared/_Layout-Ad.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Skelbimų meniu", "AdvertisementMain", "AdSubsystem", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Grįžti į pagrindinį", "Subsystem", "Declaration")</li>
                    <li>@Html.ActionLink("Peržiūrėti skelbimus", "AdvertisementList", "AdSubsystem")</li>
                    <li>@Html.ActionLink("Įterpti skelbimą", "ChooseAdType", "AdSubsystem")</li>
                    <li>@Html.ActionLink("Peržiūrėti pažymėtus skelbimus", "MarkedAdListWindow", "AdSubsystem")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right ">
                    @if (Request.IsAuthenticated)
                    {

                        <li>@Html.ActionLink("Prisijungęs: " + @Session["userName"], "", "")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Prisijungti", "Login", "Login")</li>
                        <li>@Html.ActionLink("Registruotis", "Registration", "Login")</li>
                    }
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NT valdymo sistema</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NT_Valdymo_Sistema/NT_Valdymo_Sistema/Views/Shared/_Layout-CLValuation.cshtml
@{ var userType = Session["userType"]!=null? Session["userType"]:"";} @* pasiimam session reikšmę*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nekilnojamas turtas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Request.IsAuthenticated && userType.Equals("Klientas"))
                {
                    @Html.ActionLink("NT valdymo sistema", "Subsystem", "Declaration", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (!Request.IsAuthenticated)
                {
                    @Html.ActionLink("NT valdymo sistema", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && userType.Equals("Klientas"))
                    {
                        <li>@Html.ActionLink("Pateikti NT vertinimui", "ClFillingForm", "ClValuation")</li>
                        <li>@Html.ActionLink("Peržiūrėti NT įvertinimus", "ClReviews", "ClValuation")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right ">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Prisijungęs: " + @Session["userName"], "ClientMain", "ClValuation")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Prisijungti", "Login", "Login")</li>
                        <li>@Html.ActionLink("Registruotis", "Registration", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NT valdymo sistema</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NT_Valdymo_Sistema/NT_Valdymo_Sistema/Views/Shared/_Layout-SpValuation.cshtml
@{ var userType = Session["userType"]!=null? Session["userType"]:"";} @* pasiimam session reikšmę*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nekilnojamas turtas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Request.IsAuthenticated && userType.Equals("Specialistas"))
                {
                    @Html.ActionLink("NT valdymo sistema - SPECIALISTAS", "SpecialistMain", "SpValuation", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (!Request.IsAuthenticated)
                {
                    @Html.ActionLink("NT valdymo sistema", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && userType.Equals("Specialistas"))
                    {
                        <li>@Html.ActionLink("Peržiūrėti NT užklausas bei įvertinimus", "SpRequestAndReview", "SpValuation")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right ">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Prisijungęs: " + @Session["userName"], "SpecialistMain", "SpValuation")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Prisijungti", "Login", "Login")</li>
                        <li>@Html.ActionLink("Registruotis", "Registration", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NT valdymo sistema</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NT_Valdymo_Sistema/NT_Valdymo_Sistema/Views/Shared/_Layout.cshtml
@{ var userType = Session["userType"]!=null? Session["userType"]:"";} @* pasiimam session reikšmę*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nekilnojamas turtas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Request.IsAuthenticated && userType.Equals("Klientas"))
                {
                    @Html.ActionLink("NT valdymo sistema", "Subsystem", "Declaration", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (Request.IsAuthenticated && userType.Equals("Priziuretojas"))
                {
                    @Html.ActionLink("NT valdymo sistema - PRIŽIŪRĖTOJAS", "AccountsDisplay", "Accounts", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (Request.IsAuthenticated && userType.Equals("Buhalteris"))
                {
                    @Html.ActionLink("NT valdymo sistema - BUHALTERIS", "AccountantMainWindow", "Report", new { area = "" }, new { @class = "navbar-brand" })
                }
                else if (!Request.IsAuthenticated)
                {
                    @Html.ActionLink("NT valdymo sistema", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated && userType.Equals("Klientas"))
                    {
                        <li>@Html.ActionLink("Posistemės pasirinkimas", "Subsystem", "Declaration")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right ">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Prisijungęs: " + @Session["userName"], "", "")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Prisijungti", "Login", "Login")</li>
                        <li>@Html.ActionLink("Registruotis", "Registration", "Login")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NT valdymo sistema</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>